# Generated by Django 2.2.5 on 2019-09-06 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='album',
            new_name='UserDetails',
        ),
        migrations.RemoveField(
            model_name='details',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='details',
            name='order',
        ),
        migrations.RemoveField(
            model_name='details',
            name='title',
        ),
        migrations.AddField(
            model_name='details',
            name='Address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='details',
            name='CIN',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Volume Number'),
        ),
        migrations.AddField(
            model_name='details',
            name='Phone',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Volume Number'),
        ),
        migrations.AddField(
            model_name='details',
            name='Picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
