# Generated by Django 2.2.5 on 2019-09-06 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20190906_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='CIN',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='CIN Number'),
        ),
        migrations.AlterField(
            model_name='details',
            name='Phone',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='details',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
