# Generated by Django 2.2.5 on 2019-09-06 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20190906_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='UserDetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL),
        ),
    ]
