# Generated by Django 2.2.5 on 2019-09-07 00:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20190907_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_User_Sender', models.IntegerField()),
                ('id_User_Reciver', models.IntegerField()),
                ('type_Request', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Want Give Money'), (2, 'Want Take Money')], max_length=1)),
                ('Date_Send_Request', models.DateField()),
                ('Duration_Return_Money', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Is_Readed', models.BooleanField(default=False)),
                ('Is_See', models.BooleanField(default=False)),
            ],
        ),
    ]
