# Generated by Django 2.2.5 on 2019-09-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_sendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrequest',
            name='Date_Send_Request',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='Duration_Return_Money',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='type_Request',
            field=models.CharField(choices=[(1, 'Want Give Money'), (2, 'Want Take Money')], max_length=1),
        ),
    ]
