# Generated by Django 2.2.5 on 2019-09-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20190907_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrequest',
            name='Aditionel_Information',
            field=models.TextField(default=''),
        ),
    ]
