# Generated by Django 2.2.5 on 2019-09-07 01:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_sendrequest_aditionel_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_User_Reciver', models.IntegerField()),
                ('Data_Sender', django.contrib.postgres.fields.jsonb.JSONField()),
                ('Request_Information', models.TextField()),
                ('Is_Readed', models.BooleanField(default=False)),
                ('Is_See', models.BooleanField(default=False)),
                ('Accepted_Status', models.BooleanField(default=False)),
                ('Refuse_Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='Aditionel_Information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
