# Generated by Django 2.2.5 on 2019-09-07 01:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20190907_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciverequest',
            name='Accepted_Status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='Data_Sender',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='Is_Readed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='Is_See',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='Refuse_Status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='Request_Information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Reciver',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
