# Generated by Django 2.2.5 on 2019-09-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20190907_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciverequest',
            name='Date_Send_Request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
