# Generated by Django 2.2.5 on 2019-09-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20190907_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciverequest',
            old_name='Refuse_Status',
            new_name='Accepted_Status_Giver',
        ),
        migrations.RemoveField(
            model_name='reciverequest',
            name='Accepted_Status',
        ),
        migrations.AddField(
            model_name='reciverequest',
            name='Accepted_Status_Taken',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
