# Generated by Django 2.2.5 on 2019-09-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20190908_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciverequest',
            name='Accepted_Status_Giver',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='Accepted_Status_Taken',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
