# Generated by Django 2.2.5 on 2019-09-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20190908_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciverequest',
            name='Decision_Request',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='reciverequest',
            name='id_User_Giver',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reciverequest',
            name='id_User_Taken',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sendrequest',
            name='id_User_Giver',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sendrequest',
            name='id_User_Taken',
            field=models.IntegerField(default=1),
        ),
    ]
