# Generated by Django 2.2.5 on 2019-09-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20190909_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Giver',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Taken',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='id_User_Giver',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='id_User_Taken',
            field=models.IntegerField(),
        ),
    ]
