# Generated by Django 2.2.5 on 2019-09-09 00:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_auto_20190909_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_User_Giver', models.IntegerField()),
                ('id_User_Taken', models.IntegerField()),
                ('data_User_Taken', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('data_User_Giver', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('Request_Information', models.TextField(blank=True, null=True)),
                ('Date_Create_In_History', models.DateTimeField(blank=True, null=True)),
                ('Oroginal_Amount', models.IntegerField()),
                ('Paied_Amount', models.IntegerField()),
                ('Paied_Now', models.IntegerField()),
                ('Is_Paid', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reciverequest',
            name='Date_Send_Request',
        ),
        migrations.RemoveField(
            model_name='reciverequest',
            name='Decision_Request',
        ),
        migrations.RemoveField(
            model_name='sendrequest',
            name='Date_Send_Request',
        ),
        migrations.AddField(
            model_name='reciverequest',
            name='Date_Recive_Request',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reciverequest',
            name='Decision_Status_User',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='reciverequest',
            name='ID_History',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciverequest',
            name='type_Request',
            field=models.CharField(choices=[('Want Give Money', 'Want Give Money'), ('Want Take Money', 'Want Take Money'), ('Update Paiment', 'Update Paiment')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Giver',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='Amount',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='Duration_Return_Money',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='type_Request',
            field=models.CharField(choices=[('Want Give Money', 'Want Give Money'), ('Want Take Money', 'Want Take Money'), ('Update Paiment', 'Update Paiment')], max_length=20),
        ),
    ]
