# Generated by Django 2.2.5 on 2019-09-09 04:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_auto_20190909_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciverequest',
            name='Data_Sender',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
