# Generated by Django 2.2.5 on 2019-09-09 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_auto_20190909_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciverequest',
            name='Data_Sender',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
