# Generated by Django 2.2.5 on 2019-09-09 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_auto_20190909_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Giver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usergiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Reciver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reciveuserr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senduserr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Taken',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usertaken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='id_User_Reciver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reciveuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='id_User_Sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
