# Generated by Django 2.2.5 on 2019-09-09 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_auto_20190909_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciveuserr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senduserr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='id_User_Reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senduser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='id_User_Sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciveuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
