# Generated by Django 2.2.5 on 2019-09-09 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_auto_20190909_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reciverequest',
            name='id_User_Taken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertaken', to=settings.AUTH_USER_MODEL),
        ),
    ]
