# Generated by Django 2.2.5 on 2019-09-10 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_auto_20190909_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='data_User_Giver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='datausergiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='data_User_Taken',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='datausertaken', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
