# Generated by Django 2.2.5 on 2019-09-10 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0030_auto_20190910_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='id_User_Giver',
        ),
        migrations.RemoveField(
            model_name='history',
            name='id_User_Taken',
        ),
    ]
