# Generated by Django 2.2.5 on 2019-09-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_auto_20190910_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciverequest',
            name='Oroginal_Amount',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
