# Generated by Django 2.2.5 on 2019-09-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_reciverequest_oroginal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciverequest',
            name='Oroginal_Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
