# Generated by Django 2.2.5 on 2019-09-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0034_details_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='Type_Account',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='Duration_Return_Money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
